variables:
    EOS_PATH: "/eos/user/s/srao/www"
    DOCKER_FILE: etc/docker/Dockerfile

stages:
    - documentation
    - deployment

#############################
# Documentation Compilation #
#############################

.doc:
    stage: documentation
    tags:
        - docker
    artifacts:
        paths:
            - public
        expire_in: 24 hour


# Compile Doxygen reference
cmp:doxygen:
    extends: .doc
    image: gitlab-registry.cern.ch/sft/docker/centos7:latest
    dependencies: []
    script:
        - source .gitlab/ci/init_x86_64.sh
        - source .gitlab/ci/load_deps.sh
        - mkdir -p public/usermanual
        - mkdir build
        - cd build
        - cmake -DBUILD_DOCS_ONLY=ON ..
        - make reference
        - mv reference/html ../public/reference

# Prepare user manual for MkDocs publication:
cmp:manual:
    extends: .doc
    image: gitlab-registry.cern.ch/sft/docker/centos7:latest
    dependencies: []
    script:
        - source .gitlab/ci/init_x86_64.sh
        - source .gitlab/ci/load_deps.sh
        - mkdir -p content
        - mkdir build
        - cd build
        - cmake -DBUILD_DOCS_ONLY=ON ..
        - mv mkdocs/* ../content
    artifacts:
        paths:
            - content
        expire_in: 43yrs
        # "never" is only available from 13.3 on


############################
# Documentation Deployment #
############################

# Automatically deploy documentation to the website
# Deployment job only executed for every commit.
deploy-documentation:
    stage: deployment
    tags:
      - docker
    variables:
        GIT_STRATEGY: none
    dependencies:
        - cmp:manual
        - cmp:doxygen
    # Docker image with tools to deploy to EOS
    image: gitlab-registry.cern.ch/ci-tools/ci-web-deployer:latest
    script:
        - deploy-eos
    # do not run any globally defined before_script or after_script for this step
    before_script: []
    after_script: []

# Automatically deploy documentation to the website
# Deployment job only executed for every commit.
cmp:movemanual:
    stage: deployment
    dependencies: 
        - cmp:manual
    script:
        - mkdir -p content
        - mv doc/* content
    artifacts:
        paths:
            - content
        expire_in: 43yrs
